spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true # 当实际使用的数据库不支持liquibase，如 mariadb 时，将这个参数设置为false
  datasource:
    url: jdbc:mysql://localhost:3306/${oc.database.name}?useUnicode=true&allowPublicKeyRetrieval=true&autoReconnect=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: