spring:
  application:
    name: ai-oc
  config:
    import: application-ai.yml,application-dal.yml,application-pay.yml
  web:
    resources:
      test: dd
      # 支持本地图片上传之后的链接，其中 file:///d的用于win系统，后面的file: 适用于mac/linux系统
      static-locations:
        - classpath:/static/
        - file:///d:${oc.img.abs-tmp-path}
        - file:${oc.img.abs-tmp-path}
  servlet:
    multipart:
      enabled: true
      max-file-size: 8MB  # 单个文件上传大小限制
      max-request-size: 10MB # 总请求大小限制
oc:
  jwt:
    issuer: oc # 签发者
    secret: hello_offer # 签名密钥
    expire: 2592000000 # jwt的有效期，默认30天
  site:
    login-qr-img: https://spring.hhui.top/spring-blog/imgs/info/wx.jpg
    website-name: 来个OC
    web-site-logo: https://spring.hhui.top/spring-blog/css/images/avatar.jpg
    web-site-host: http://localhost
    vip-price: # 会员价格
      - 1999
      - 5999
      - 13999
      - 29999
  img:
    abs-tmp-path: /tmp/storage/
    web-img-path: /oc/img/
    cdn-host: http://localhost:8080
  database:
    name: oc

# 修改日志级别
logging:
  level:
    com:
      git:
        hui: info
server:
  port: 8080
  compression:
    enabled: true # 开启返回结果压缩，减少传输耗时
    min-response-size: 2KB

