spring:
  application:
    name: ai-oc
  config:
    import: application-oc.yml,application-ai.yml,application-dal.yml,application-pay.yml
  web:
    resources:
      # 支持本地图片上传之后的链接，其中 file:///d的用于win系统，后面的file: 适用于mac/linux系统
      static-locations:
        - classpath:/static/
        - file:///d:${oc.img.abs-tmp-path}
        - file:${oc.img.abs-tmp-path}
  servlet:
    multipart:
      enabled: true
      max-file-size: 8MB  # 单个文件上传大小限制
      max-request-size: 10MB # 总请求大小限制

  ai:
    mcp:
      server:
        name: 校招派
        type: sync
        instructions: "校招派是一个专业的校招信息推荐服务，可以根据您输入的个人求职意愿如求职公司类型、工作地点要求、求职岗位、校招或者实习、毕业年限，自动匹配返回最优的校招信息列表，让你不再错过招聘信息"
        sse-endpoint: /api/sse
        sse-message-endpoint: /api/mcp/messages
        version: 1.0.0
        capabilities:
          tool: true # 是否支持工具
          resource: true # 是否支持资源
          prompt: true # 是否支持提示词
          completion: true # 是否支持补全


# 修改日志级别
logging:
  level:
    com:
      git:
        hui: info
server:
  port: 8080
  compression:
    enabled: true # 开启返回结果压缩，减少传输耗时
    min-response-size: 2KB

