spring:
  application:
    name: ai-oc
  config:
    import: application-ai.yml,application-dal.yml


  # jap配置
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
oc:
  jwt:
    issuer: oc # 签发者
    secret: hello_offer # 签名密钥
    expire: 2592000000 # jwt的有效期，默认30天
  site:
    login-qr-img: https://spring.hhui.top/spring-blog/imgs/info/wx.jpg
    website-name: 来个OC
    web-site-logo: https://spring.hhui.top/spring-blog/css/images/avatar.jpg
    web-site-host: http://localhost
    vip-periods: 360

# 修改日志级别
logging:
  level:
    com:
      git:
        hui: info
