spring:
  application:
    name: ai-oc
  config:
    import: application-oc.yml,application-ai.yml,application-dal.yml,application-pay.yml
  web:
    resources:
      # 支持本地图片上传之后的链接，其中 file:///d的用于win系统，后面的file: 适用于mac/linux系统
      static-locations:
        - classpath:/static/
        - file:///d:${oc.img.abs-tmp-path}
        - file:${oc.img.abs-tmp-path}
  servlet:
    multipart:
      enabled: true
      max-file-size: 8MB  # 单个文件上传大小限制
      max-request-size: 10MB # 总请求大小限制

# 修改日志级别
logging:
  level:
    com:
      git:
        hui: info
server:
  port: 8080
  compression:
    enabled: true # 开启返回结果压缩，减少传输耗时
    min-response-size: 2KB

