spring:
  datasource:
    # 本地开发环境，使用h2数据库，减少外部依赖项
    url: jdbc:h2:file:${user.dir}/datas/${oc.database.name};DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  # jap配置
  jpa:
    hibernate:
      # 根据实体类更新表结构（默认）
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect